# Configura cada nodo hospitalario, Consul, tiempos de coordinacion y health checks.
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: hospital-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: hospital-service
        instance-id: ${spring.application.name}-${node.id}
        register: true
        fail-fast: false
        health-check-path: /actuator/health
        prefer-ip-address: true
        ip-address: ${NODE_HOST:localhost}
  task:
    scheduling:
      pool:
        size: 5

node:
  id: ${NODE_ID:1}
  host: ${NODE_HOST:localhost}

tcp:
  port: ${TCP_PORT:9001}
  connect-timeout-ms: 800
  read-timeout-ms: 1200

nodes:
  config-file: ${NODES_CONFIG_FILE:nodes.json}

coordinacion:
  heartbeat-ms: 2000
  timeout-heartbeat-ms: ${TIMEOUT_HEARTBEAT_MS:15000}
  espera-respuesta-eleccion-ms: 1800
  sincronizacion-cristian-ms: 8000
  maximo-logs: 300
  ajustar-reloj-sistema: ${AJUSTAR_RELOJ_SISTEMA:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info
